site_name: Dev Documentation
docs_dir: src
site_url: https://docs.cozy.io/
site_dir: docs/en
site_favicon: img/favicon.png
repo_url: https://github.com/cozy/cozy.github.io/
edit_uri: edit/dev/src/
site_description: Cozy documentation
site_author: CozyCloud - https://cozy.io
extra_css:
- css/extra.css
- css/highlight_theme.css
extra_javascript:
- extra.js
pages:
- Home: index.md
- Tutorials:
  - Create your application: tutorials/app.md
  - Develop a connector: tutorials/konnector.md
- How-to:
  - Self-Host:
    - Debian: howTos/selfHost/debian.md
  - Dev:
    - Make a mobile app using cordova: howTos/dev/cordova.md
    - Connect a mobile app to your local stack: howTos/dev/connect-mobile-app-local-stack.md
    - Send and receive e-mails in development: howTos/dev/sendmail.md
  - Synchronize:
    - Install Cozy Drive on GNU/Linux: howTos/sync/linux.md
- References:
  - Cozy Architecture: references/architecture.md
  - Our Front-End Git Flow: references/git-flow.md
  - Stack and tools:
    - null # This is filled automatically via add_external_docs.py
theme: mkdocs
theme_dir: cozy-theme
markdown_extensions:
  - admonition
  - codehilite
  - extra
  - footnotes
  - meta
  - sane_lists
  - smarty
  - toc:
      permalink: True
