site_name: Cozy Documentation
docs_dir: src
site_url: https://docs.cozy.io/
site_dir: docs/en
site_favicon: img/favicon.png
repo_url: https://github.com/cozy/cozy-docs-v3
edit_uri: edit/master/src/
site_description: Cozy documentation
site_author: CozyCloud - https://cozy.io
extra_css: [extra.css]
pages:
  - Home: index.md
  - Use:
    - "User guide": use/index.md
  - Synchronize:
    - 'Stay in sync': sync/index.md
    - 'Synchronize your phone': sync/phone.md
    - 'Synchronize your computer': sync/desktop.md
  - Download: download/index.md
  - Install:
    - "Install Cozy on your own server": install/index.md
    - "Manual installation": install/manual.md
  - Develop:
    - "Let's hack some code": dev/index.md
    - "Architecture": dev/intro.md
    - "Create your first app": dev/app.md
    - "Develop a connector": dev/konnector.md
    - "Create a mobile app with cordova": dev/cordova.md
theme: readthedocs
theme_dir: 'cozy-theme'
markdown_extensions:
  - admonition
  - codehilite
  - extra
  - footnotes
  - markdown_i18n:
      i18n_lang: en_US
      i18n_dir: i18n
  - sane_lists
  - smarty
  - toc:
      permalink: True

