site_name: Cozy Developer Documentation
docs_dir: src
site_url: https://docs.cozy.io/
site_dir: docs/en
site_favicon: img/favicon.png
repo_url: https://github.com/cozy/cozy.github.io/
edit_uri: edit/dev/src/
site_description: Cozy documentation
site_author: CozyCloud - https://cozy.io
extra_css:
- css/extra.css
extra_javascript:
- extra.js
nav:
- Home: index.md
- Tutorials:
  - Create Your Application: tutorials/app.md
  - Develop a Connector: tutorials/konnector.md
  - Self-Host on Debian: tutorials/selfhost-debian.md
- How-to:
  - Dev:
    - Run an App in a Cozy using Docker: howTos/dev/runCozyDocker.md
    - Use Hot Module Replacement in Your App: howTos/dev/hmr.md
    - Make a Mobile App Using Cordova: howTos/dev/cordova.md
    - Connect a Mobile App to Your Local Stack: howTos/dev/connect-mobile-app-local-stack.md
    - Send and Receive E-mails in Development: howTos/dev/sendmail.md
  - Synchronize:
    - Install Cozy Drive on GNU/Linux: howTos/sync/linux.md
- References:
  - Technical introduction to the Cozy platform: references/tech-intro.md
  - Our Front-End Git Flow: references/git-flow.md
  - Stack and tools:
    - null # This is filled automatically via add_external_docs.py
theme:
  custom_dir: cozy-theme
  name: material
  palette:
    primary: blue
    accent: blue
  logo:
    icon: cloud
  font:
    text: Lato
    code: Ubuntu Mono
markdown_extensions:
- admonition
- codehilite
- extra
- footnotes
- meta
- sane_lists
- smarty
- toc:
    permalink: true
